name: "Build Android APK"

on:
  workflow_dispatch:
    inputs:
      BASE_URL:
        description: "Server Base Url"
        required: true
        default: ""

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "15.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.0"

      - name: Build APK
        run: flutter clean && flutter pub get && flutter build apk --release --dart-define=CUSTOM_ENV=${{ github.event.inputs.BASE_URL }}

      - name: Push to GH Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
